version: '2'
volumes:
  db:
  storage:
  logo:
  public:

services:
  db:
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - default
    environment:
      - MYSQL_DATABASE:{$MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD:{$MYSQL_ROOT_PASSWORD}

  app:
    image: invoiceninja/invoiceninja
    restart: always
    depends_on:
      -  db
    volumes:
      -  storage:/var/www/app/storage
      -  logo:/var/www/app/public/logo
      -  public:/var/www/app/public
    networks: 
      - default
    environment:
      - APP_DEBUG:{$APP_DEBUG}
      - APP_URL:{$APP_URL}
      - APP_KEY:{$APP_KEY}
      - APP_CIPHER:{$APP_CIPHER}
      - DB_USERNAME:{$DB_USERNAME}
      - DB_PASSWORD:{$DB_PASSWORD}
      - DB_HOST:{$DB_HOST}
      - DB_DATABASE:{$DB_DATABASE}
      - MAIL_HOST:{$MAIL_HOST}
      - MAIL_USERNAME:{$MAIL_USERNAME}
      - MAIL_PASSWORD:{$MAIL_PASSWORD}
      - MAIL_DRIVER:{$MAIL_DRIVER}
      - MAIL_FROM_NAME:{$MAIL_FROM_NAME}
      - MAIL_FROM_ADDRESS:{$MAIL_FROM_ADDRESS}

  web:
    image: nginx
    volumes:
      -  /home/rancher/invoiceNinjaNginx.conf:/etc/nginx/nginx.conf:ro
      -  storage:/var/www/app/storage
      -  logo:/var/www/app/public/logo
      -  public:/var/www/app/public
    expose: # Expose ports without publishing them to the host machine - they’ll only be accessible to linked services.
      - "80"
    ports: # Delete if you want to use reverse proxy
      - 8000:80
    networks:
#      - web        # uncomment if you want to use  external network (reverse proxy for example)
      - default

  cron:
    image: invoiceninja/invoiceninja
    volumes:
      -  storage:/var/www/app/storage
      -  logo:/var/www/app/public/logo
      -  public:/var/www/app/public
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 300s
      while /bin/true; do
        ./artisan ninja:send-invoices
        ./artisan ninja:send-reminders
        sleep 1d
      done
      EOF'
    networks:
      - default
    environment:
      - APP_DEBUG:{$APP_DEBUG}
      - APP_URL:{$APP_URL}
      - APP_KEY:{$APP_KEY}
      - APP_CIPHER:{$APP_CIPHER}
      - DB_USERNAME:{$DB_USERNAME}
      - DB_PASSWORD:{$DB_PASSWORD}
      - DB_HOST:{$DB_HOST}
      - DB_DATABASE:{$DB_DATABASE}
      - MAIL_HOST:{$MAIL_HOST}
      - MAIL_USERNAME:{$MAIL_USERNAME}
      - MAIL_PASSWORD:{$MAIL_PASSWORD}
      - MAIL_DRIVER:{$MAIL_DRIVER}
      - MAIL_FROM_NAME:{$MAIL_FROM_NAME}
      - MAIL_FROM_ADDRESS:{$MAIL_FROM_ADDRESS}

