.catalog:
  name: Gitlab Community
  version: 12.0.2-ce.0
  description: |
    GitLab Community Edition (CE) is an open source end-to-end software development platform with built-in version control, issue tracking, code review, CI/CD, and more. Self-host GitLab CE on your own servers, in a container, or on a cloud provider.
  minimum_rancher_version: v0.56.0
  maintainer: "FRITZ|FRITZ <fritz@fritztech.net>"
  uuid: gitlab-0
  questions:
    - variable: "gitlab_hostname"
      description: "Gitlab hostname (without uri scheme http:// or https://)"
      label: "Hostname:"
      required: true
      default: "git.example.com"
      type: "string"
    - variable: "registry_gitlab_hostname"
      description: "Registry Gitlab hostname (without uri scheme http:// or https://)"
      label: "Registry hostname:"
      required: true
      default: "registry.example.com"
      type: "string"
    - variable: "gitlab_omnibus_prefix"
      label: "Gitlab external_url prefix:"
      description: |
        This is needed for the docker-compose file to set the correct external_url
      default: 'http://'
      required: true
      type: "enum"
      options:
        - 'http://'
        - 'https://'
    - variable: "ssh_port"
      description: "SSH port to expose on host. Will be used to bind TCP"
      label: "SSH port:"
      required: true
      default: 22
      type: "int"
    - variable: "volumedriver"
      description: "Choose the Volume Driver being used.(Option: local or rancher-nfs)"
      label: "Volume Driver:"
      required: true
      default: local
      type: "enum"
      options:
        - local
        - rancher-nfs
    - variable: "gitlab_letsencrypt"
      description: "Enable letsencrypt"
      required: true
      default: true
      type: boolean
    - variable: "gitlab_nginx_port"
      description: "Port for webserver"
      required: true
      default: 443
      type: "int"
    - variable: "gitlab_https"
      description: "Enable HTTPS"
      required: true
      default: true
      type: boolean 

gitlab-server:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 3000
    healthy_threshold: 2

