name: InvoiceNinja
description: |
  The leading free open-source online invoicing app for freelancers & businesses. Invoice, accept payments, track expenses, create proposals, & time-tasks.
version: v4.5.13
category: Invoicing
maintainer: <fritz@fritztech.net>
license: ATTRIBUTION ASSURANCE LICENSE
projectURL: invoiceninja.org
